@startuml classDiagram
package javax.swing {
    class JFrame <<library>>
    class JPanel <<library>>

    package plaf.basic {
        class BasicScrollBarUI <<library>>
    }
}

class Main {
    + main : void
}

package logic {
    class NoticeCrawler {
        - homepage : String

        + noticeListCrawler() : void
        - contentsCrawler(noticeSubjects : Elements) : String
    }
}

package ui {
    class CJUShuttlePlusFrame extends javax.swing.JFrame {
        + CJUShuttlePlusFrame()
    }

    class CJUShuttlePlusNoticePanel extends javax.swing.JPanel {
        - titlePanel : JPanel
        - noticeScrollPane : JScrollPane

        # CJUShuttlePlusNoticePanel()
        - createTitlePanel() : void
        - createNoticePanel() : void
    }
}

package utils {
    class Constants {
        + FONT : String
        + NOTICE_TITLE : String
        + CJU_MAIN_BLUE : Color
        + CLEAR_COLOR : Color
        + CJU_PANEL_BACKGROUND : Color
        + CJU_CONTENT_BACKGROUND : Color
        + NOTICE_BORDER_COLOR : Color

        - Constants()
    }

    class CustomScrollBarUI extends javax.swing.plaf.basic.BasicScrollBarUI {
        # createDecreaseButton() : JButton
        # createIncreaseButton() : JButton
        - createInvisibleButton() : JButton
        # paintThumb() : void
        + getPreferredSize(c : JComponent) : Dimension
        # paintTrack(g : Graphics, c : JComponent, trackBounds : Rectangle) : void
        # getTrackBounds() : Rectangle
    }

    class ManagementCSV {
        - readCSV() : String
        + writeCSV(hashMap : Map<Integer, ArrayList<String>>) : void
        + createHashMap() : Map<Integer, String[]>
    }

    class RoundedPanel extends javax.swing.JPanel {
        - color : Color
        - radius : int

        + RoundedPanel(color : Color, radius : int)
        # paintComponent(g : Graphics) : void
        # paintBorder(g : Graphics) : void
    }
}
@enduml