@startuml class

top to bottom direction
skinparam linetype ortho

package javax.swing {
    class JFrame <<library>>
    class JPanel <<library>>

    package plaf.basic {
        class BasicScrollBarUI <<library>>
    }
}

class Main {
  + Main(): 
  + main(String[]): void
}

package logic {
    class NoticeCrawler {
    + NoticeCrawler(): 
    - homepage: String
    + noticeListCrawler(): void
    - contentsCrawler(Elements): String
    }
}

package ui {
    class CJUShuttlePlusFrame extends javax.swing.JFrame {
        + CJUShuttlePlusFrame(): 
    }

    class CJUShuttlePlusNoticePanel extends javax.swing.JPanel {
        # CJUShuttlePlusNoticePanel(): 
        - noticeScrollPane: JScrollPane
        - titlePanel: JPanel
        - createTitlePanel(): void
        - createNoticePanel(): void
    }
}

package utils {
    class Constants {
        - Constants(): 
        + FONT: String
        + CLEAR_COLOR: Color
        + CJU_MAIN_BLUE: Color
        + NOTICE_BORDER_COLOR: Color
        + NOTICE_TITLE: String
        + CJU_CONTENT_BACKGROUND: Color
        + CJU_PANEL_BACKGROUND: Color
    }

    class CustomScrollBarUI extends javax.swing.plaf.basic.BasicScrollBarUI {
        + CustomScrollBarUI(): 
        # paintThumb(Graphics, JComponent, Rectangle): void
        + getPreferredSize(JComponent): Dimension
        # getTrackBounds(): Rectangle
        # createIncreaseButton(int): JButton
        # createDecreaseButton(int): JButton
        # paintTrack(Graphics, JComponent, Rectangle): void
        - createInvisibleButton(): JButton
    }

    class ManagementCSV {
        + ManagementCSV(): 
        - readCSV(): String
        + createHashMap(): Map<Integer, String[]>
        + writeCSV(Map<Integer, ArrayList<String>>): void
    }

    class RoundedPanel extends javax.swing.JPanel {
        + RoundedPanel(Color, int): 
        - color: Color
        - radius: int
        # paintBorder(Graphics): void
        # paintComponent(Graphics): void
    }
}

CJUShuttlePlusFrame        -[#595959,dashed]->  CJUShuttlePlusNoticePanel : "«create»"
CJUShuttlePlusNoticePanel  -[#595959,dashed]->  CustomScrollBarUI         : "«create»"
CJUShuttlePlusNoticePanel  -[#595959,dashed]->  ManagementCSV             : "«create»"
CJUShuttlePlusNoticePanel  -[#595959,dashed]->  NoticeCrawler             : "«create»"
CJUShuttlePlusNoticePanel  -[#595959,dashed]->  RoundedPanel              : "«create»"
Main                       -[#595959,dashed]->  CJUShuttlePlusFrame       : "«create»"
NoticeCrawler              -[#595959,dashed]->  ManagementCSV             : "«create»"

@enduml
